### PR TITLE
Merge pull requests 8 and 9

### PR DESCRIPTION
**Pull request by arirusso**
@petems This branch merges https://github.com/petems/mplayer-ruby/pull/8 and https://github.com/petems/mplayer-ruby/pull/9 and resolves conflicts

Thanks

### CODE REVIEW

**Comment by arirusso** [comment]
@petems Thank you!

Is it possible to do gem updates using this fork?  Might need to give it a different name...

**Comment by petems** [comment]
@arirusso Sure! It's been a while tbh, I forgot I was maintaining this heh

I'll open an issue, I've also added you as a maintainer, general policy is merges are ok if:

1) Travis is passing
2) Backwards compatible change
OR
3) Minor doc change

For non-backwards compatible, we can discuss and/or do a major release bump.

**Comment by arirusso** [comment]
@petems, thanks!  Going to be doing a project on top of this gem, so that'll be helpful

In terms of just the gem itself though, I see that you're an owner on the original one (https://rubygems.org/gems/mplayer-ruby) so I suppose a new gem isn't necessary.  

It's not a huge rush but getting the gem up-to-date with this repo would be useful bc my project relies on https://github.com/petems/mplayer-ruby/pull/9

Thanks so much for the quick response

**Comment by petems** [comment]
Oh wow, it has been a long time, I forgot he added me to the gem too! :smile: 

Should be able to get this done EOW, if I don't by the end of the week bug me to remind me :+1:

**Comment by arirusso** [comment]
Awesome, thank you so much

**Comment by petems** [comment]
Done! :+1:

**Comment by arirusso** [comment]
Rubygems is saying the new version was built on 2/1/2010... ?  https://rubygems.org/gems/mplayer-ruby/versions/0.2.0

The good news is, all of the changes appear to be in the gem so there's no urgency (for me anyway) in figuring out the problem

Thank you again

**Pull request merged**
